name: Build APK

on:
  push:
    branches:
      - main  # or "master" or any branch you use

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential python3-pip python3-setuptools zip unzip openjdk-17-jdk git
        pip install --user buildozer cython

    - name: Accept Android SDK licenses
      run: |
        mkdir -p $HOME/.android
        echo '8933bad161af4178b1185d1a37fbf41ea5269c55' > $HOME/.android/repositories.cfg
        yes | sdkmanager --licenses || true

    - name: Build the APK
      run: |
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: built-apk
        path: bin/*.apk
